apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kubernetes resources to be managed by kustomize
resources:
 - db-config.yaml
 - db-depl.yaml
 - db-service.yaml

  
# kubectl apply -k .
# kubectl apply -k /root/code/k8s/
# or
# kustomize build /root/code/k8s/ | kubectl apply -f -
