resources:
  - mongo-depl.yaml
  - api-depl.yaml
  - mongo-service.yaml

patches:
 - target:
      kind: Deployment
      name: mongo-deployment
    patch: |-
      - op: remove
        path: /spec/template/metadata/labels/org